language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
android:
    components:
        - build-tools-24.0.0
        - extra
        - sys-img-armeabi-v7a-android-22
        - sys-img-x86-android-17

before_install:
 - chmod +x gradlew